Home:
  text: We develop <span className="text-green-300">Technology</span> to
    protect what <span className="text-green-300">Matters</span> most
    to you.
  img:
    bgName: headerOne
    location: assets/img.header2.webp

Our Tech:
  text: Text for header
  img:
    bgName: headerTwo
    location: assets/img.header2.webp

Faq:
  text: Text for header
  img:
    bgName: headerTwo
    location: assets/img.header2.webp

Contact Us:
  text: Text for header
  img:
    bgName: headerTwo
    location: assets/img.header2.webp

Careers:
  text: Text for header
  img:
    bgName: headerTwo
    location: assets/img.header2.webp
