- Title: Formulating Idea
  Date: May 2016
  Text: Seth began formulating the idea to use non contact vital sign sensors in various applications.

- Title: Patent searches
  Date: August 2016
  Text: First patent searches were conducted.

- Title: NASA Engineers
  Date: March 2017
  Text: NASA engineers join our team.

- Title: Patent Filed.
  Date: June 2017
  Text: Our first patent was filed.

- Title: Money raised
  Date: July 2017
  Text: Our first seed round raised. Company is incorporated.

- Title: Proof of concept finished
  Date: May 2018
  Text: Our first live demo, and proof of concept were completed.

- Title: We grow
  Date: March 2019
  Text: Fullstaff is added into engineering team.

- Title: More money
  Date: June 2019
  Text: We raised 7 figure seed round with original invenstors.

- Title: MVP
  Date: November 2019
  Text: Recieved first completed prototype MVP from the manufacturing plant.

- Title: More growing
  Date: March 2020
  Text: Added full time staff to the business team.

- Title: Engage design
  Date: March 2020
  Text: Engaged design and manufacturing firms as plans to bring the first product to market in 2021
